language: python
addons:
  apt:
    packages:
      - bowtie2
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.6"
      install:
        - pip install pytest-flake8
        - pip install .
      script:
        - flake8 nuc_processing test setup.py
      after_success: []
install:
  - pip install pytest-cov codecov
  - pip install .
script:
  - pytest --cov=nuc_processing
after_success:
  - codecov
